"""Shared typing contract for dynamic probe modules.

Probe modules are loaded by the dataset registry and may produce prompts through
an ordinary iterator or an asynchronous iterator.  ``ModuleProtocol`` captures
the common surface without forcing existing modules to inherit from a concrete
base class.
"""

import asyncio
from collections.abc import AsyncIterator, Iterator
from typing import Any, Protocol, TypeAlias, runtime_checkable

ModuleOutput: TypeAlias = Iterator[str] | AsyncIterator[str]


@runtime_checkable
class ModuleProtocol(Protocol):
    """Structural interface implemented by dynamic probe modules.

    Implementations receive the configured prompt groups, the queue used to
    exchange messages with external tools, and module-specific options.  The
    ``apply`` method yields prompt strings either synchronously or
    asynchronously.
    """

    prompt_groups: list[Any]
    tools_inbox: asyncio.Queue[Any]
    opts: dict[str, Any]

    def apply(self) -> ModuleOutput:
        """Yield prompts generated by the module."""
        ...
